version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "bcm-works"
    labels:
      - "deps"
      - "ai-generated"
    groups:
      deps-ghactions:
        patterns:
          - "*"
    target-branch: "main"
    pull-request-branch-name:
      separator: "-"
      prefix: "fix-deps-ghactions-"
      branch-name-case: "lowercase"
  - package-ecosystem: "deno"
    directory: "/"
    exclude-paths:
      - ".prototypes/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "bcm-works"
    labels:
      - "deps"
      - "ai-generated"
    groups:
      deps-deno:
        patterns:
          - "*"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    target-branch: "main"
    pull-request-branch-name:
      separator: "-"
      prefix: "fix-deps-deno-"
      branch-name-case: "lowercase"
  - package-ecosystem: "gomod"
    directory: "/src/cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "bcm-works"
    labels:
      - "deps"
      - "ai-generated"
    groups:
      deps-gomod:
        patterns:
          - "*"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    target-branch: "main"
    pull-request-branch-name:
      separator: "-"
      prefix: "fix-deps-gomod-"
      branch-name-case: "lowercase"
